### ISSUE TITLE
Time and Temp display options

### ISSUE THREAD

**Issue by vmitchell85** [spatie/laravel-dashboard-time-weather-tile#1]
Would a PR providing options to change the time display and/or providing options for displaying Fahrenheit instead of Celsius be accepted?

Wanted to make sure it's something that would be considered before building options for it.

Thanks,
Vince

**Comment by freekmurze** [comment]
If it is implemented in a clean, backwards compatible way, I'll consider merging it in. 

Even if it's not merged, you could opt to just create a new, separate tile 👍

**Comment by vmitchell85** [comment]
Thanks
