### ISSUE TITLE
Tile not showing temperture

### ISSUE THREAD

**Issue by ghost** [spatie/laravel-dashboard-time-weather-tile#11]
Hi there Spatie,

I just installed this tile and it shows on the dashboard. But it's not showing the outside temperature and its showing the emoji with the glass.

I added my openweather API key which I received after signing up to the service and got the latitude and longitude from buienradar.nl

**this is how my env looks (I changed the API key)**
OPEN_WEATHER_MAP_KEY=23f6130b190e1de0ac4z0047x4c0650c
BUIENRADAR_LATITUDE=52.30803780879979
BUIENRADAR_LONGITUDE=4.972515106201172

Of course I followed the rest of the instructions.
Any idea?

**Comment by dotRamsey** [comment]
After trying out another tile it seems to be a problem with the open weather API not returning any data.

**Comment by ghost** [comment]
Manually running the commands to fetch data seems to work just fine. But no change on the tile.

**Comment by ghost** [comment]
Here is a quick look at how the tile looks at the moment.
![image](https://user-images.githubusercontent.com/79672475/126103572-9116c76c-d3d4-42b8-8618-56cfb858d613.png)
